import RootProvider from "@/components/RootProvider/RootProvider";
import "./globals.css";
import type { Metadata } from "next";
import DirectoriesNavigation from "@/modules/DirectoriesNavigation/DirectoriesNavigation";
import ContextMenu from "@/components/ContextMenu/ContextMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RootProvider>
        <ContextMenu />
        <div id="portalContextMenu" />
        <DirectoriesNavigation />
      </RootProvider>
    </html>
  );
}
